title: "CyberCore – HLS Berlin"
description: "Informatik Lernplattform · E-Phase · Informatiksysteme"
baseurl: "/inf"
url: "https://andirz.github.io"

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
